from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/process', methods=['POST'])
def process_request():
    data = request.json
    question = data.get('question')

    # Simulate processing the question
    answer = f"Answer to '{question}' generated by Ollama"

    return jsonify({"answer": answer})

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5001)