version: '3.8'

services:
  flask-app:
    build:
      context: ./  #build flask app
      dockerfile: Dockerfile
    container_name: recipe-app-container
    ports:
      - "8080:8080"
    depends_on:
      - ollama-container
    networks:
      - app-network

    #command: gunicorn --bind 0.0.0.0:8080 app:app

  ollama-container:
    build:
      context: ./Ollama #build ollama container
      dockerfile: Dockerfile
    container_name: ollama-container
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge