version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    restart: on-failure
    volumes:
      - .ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network

  flask-server:
    build:
      context: ./  # Build Flask app
      dockerfile: Dockerfile
    container_name: recipe-app-container
    image: recipe-name-container:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - FLASK_ENV=development  # Enable development mode
      - FLASK_DEBUG=1  # Enable debug mode
    command: flask run --host=0.0.0.0 --port=8080  # Start Flask in debug mode

networks:
  app-network:
    driver: bridge
