services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    restart: on-failure
    volumes:
      - .ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network

  flask-server:
    build:
      context: ./  #build flask app
      dockerfile: Dockerfile
    container_name: recipe-app-container
    image: recipe-name-container:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local