version: '3.4'

services:
  flask-app:
    build:
      context: ./Flask_server  # Specify the folder for Flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ollama-container
    networks:
      - app-network

    ollama-container:
      build:
        context: ./Ollama  # Specify the folder for Ollama
        dockerfile: Dockerfile
      ports:
        - "5001:5001"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge